#!/usr/bin/env bash
# Build the isolated environment that can load Qwen-Image-2.1.
#
# The stock .venv carries diffusers 0.36.0, which has no QwenImage21Pipeline
# (the class arrived in the 0.37.0.dev0 line). Upgrading .venv in place would
# also drag torch from 2.5.1+cu121 to 2.14.0 underneath the two legacy
# backends that currently work, so the new stack lives beside them instead.
#
# Usage:  ./scripts/setup_qi21_env.sh            # create/update .venv-qi21
#         EC_QI21_VENV=/path ./scripts/setup_qi21_env.sh
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
VENV_DIR="${EC_QI21_VENV:-$REPO_DIR/.venv-qi21}"
LOCK="$REPO_DIR/requirements_qi21.txt"
PYTHON_BIN="${EC_PYTHON:-python3}"

test -f "$LOCK" || { echo "missing lock file: $LOCK" >&2; exit 1; }

echo "[qi21] creating $VENV_DIR"
"$PYTHON_BIN" -m venv --system-site-packages --copies "$VENV_DIR"
# Keep the interpreter the one we just chose; activation on this box has been
# observed to leave PATH pointing at an unrelated distribution's python.
export VIRTUAL_ENV="$VENV_DIR"
export PATH="$VENV_DIR/bin:$PATH"
VPY="$VENV_DIR/bin/python"
"$VPY" -m pip install --quiet --upgrade pip

# This machine's user-level pip config can carry an NVIDIA-managed extra index
# that does not resolve off their network; a venv-level config outranks it.
cat > "$VENV_DIR/pip.conf" <<'PIPCONF'
# pip settings for THIS environment only.
#
# A user-level pip config autogenerated by "NVIDIA PyIndex" can add an extra
# index (pypi.ngc.nvidia.com) plus a matching trusted-host entry. That host does
# not resolve off the NVIDIA network, so installs in this venv stall retrying it
# and can fail outright. A venv-level config outranks the user-level one, which
# keeps this environment buildable without touching global pip configuration.
[global]
index-url = https://pypi.org/simple
extra-index-url = https://pypi.org/simple
trusted-host = pypi.org
PIPCONF
echo "[qi21] wrote $VENV_DIR/pip.conf"

echo "[qi21] installing the pinned stack"
"$VPY" -m pip install -r "$LOCK"

echo "[qi21] verifying the model class is importable"
"$VPY" - <<'PYCHECK'
import diffusers
from diffusers import QwenImage21Pipeline  # noqa: F401  the whole point of this env
print(f"[qi21] ok: diffusers {diffusers.__version__}, QwenImage21Pipeline available")
PYCHECK

cat <<'NOTE'

[qi21] done. Launch the application with this interpreter:
         EC_PYTHON=$VENV_DIR ./scripts/run.sh
       Loading Qwen-Image-2.1 also needs its weights, which the app will
       not fetch until the upstream terms have been accepted:
         $VENV_DIR/bin/python scripts/accept_model_license.py \
             --model Qwen/Qwen-Image-2.1 --yes
NOTE
